# Generated by Django 5.1 on 2024-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='image',
        ),
        migrations.AddField(
            model_name='laptop',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='show_on_home_page',
            field=models.BooleanField(default=True),
        ),
    ]
