# Generated by Django 5.1 on 2024-08-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_remove_laptop_base_price_remove_laptop_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='show_on_home_page',
        ),
        migrations.AddField(
            model_name='laptop',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='image',
            field=models.ImageField(default=1, upload_to='laptops/'),
            preserve_default=False,
        ),
    ]
