# Generated by Django 5.1 on 2024-09-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0004_rename_review_text_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
    ]
